Repository micronaut-projects/micronaut-views, pull requests merged in 2020-12, with the labels that each got.

#134 [views] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#135 [views] Update common files for branch 2.1.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#137 bump up micronaut-gradle-plugins to 2.0.13 and micronaut docs to 1.0.25
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#136 MANTAINING.md and github actions
  .github/workflows/release-notes.yml
  MAINTAINING.md
Labels: relates-to: build

#140 build: bump up micronaut test to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#141 ci: downgrade github action create-pull-request to 3.5.1
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#143 [views] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#146 Fix typo in views.adoc
  src/main/docs/guide/views.adoc
Labels: type: docs

#144 build: micronaut-test to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#148 Thymeleaf 3.0.12 Release Notes
  gradle.properties
Labels: type: dependency-upgrade

#151 build: micronaut-security to 2.2.1
  test-suite/build.gradle
  views-core/build.gradle
Labels: type: dependency-upgrade
