Repository micronaut-projects/micronaut-views, pull requests merged in 2021-12, with the labels that each got.

#322 build: bump up gradle to 7.3.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#329 [views] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build

#331 wrap bom dependencies in constraints
  views-bom/build.gradle
Labels: type: bug, relates-to: build

#332 [views] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#335 build: update gradle wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradlew
Labels: relates-to: build

#320 feature: Jte support
  config/checkstyle/suppressions.xml
  gradle.properties
  settings.gradle
  src/main/docs/guide/toc.yml
  src/main/docs/guide/views/templates/jte.adoc
  views-bom/build.gradle
  views-jte/build.gradle
  views-jte/src/main/java/io/micronaut/views/jte/HtmlJteViewsRenderer.java
  views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
  views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfiguration.java
  views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfigurationProperties.java
  views-jte/src/main/java/io/micronaut/views/jte/PlainJteViewsRenderer.java
  views-jte/src/test/groovy/io/micronaut/docs/JteController.groovy
  views-jte/src/test/groovy/io/micronaut/docs/JteViewRendererSpec.groovy
  views-jte/src/test/groovy/io/micronaut/docs/Person.groovy
  views-jte/src/test/resources/logback.xml
  views-jte/src/test/resources/views/home.jte
Labels: type: enhancement

#341 doc: don't use Micronaut as a noun
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/views.adoc
  src/main/docs/guide/views/graal.adoc
  src/main/docs/guide/views/handlebars.adoc
  src/main/docs/guide/views/model.adoc
  src/main/docs/guide/views/security/csp.adoc
  src/main/docs/guide/views/templates/freemarker.adoc
  src/main/docs/guide/views/templates/pebble.adoc
  src/main/docs/guide/views/templates/rocker.adoc
  src/main/docs/guide/views/templates/soy.adoc
  src/main/docs/guide/views/templates/soy/soyfeaturesremaining.adoc
  src/main/docs/guide/views/templates/soy/soyusage.adoc
  src/main/docs/guide/views/templates/thymeleaf.adoc
  src/main/docs/guide/views/templates/velocity.adoc
Labels: type: docs
