Repository micronaut-projects/micronaut-views, pull requests merged in 2021-09, with the labels that each got.

#279 build: update to gradle 7.2
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#287 doc: clarify SecurityViewModelProcessor is typed
  src/main/docs/guide/views/security/security-model-enhancement.adoc
Labels: type: docs

#295 Pullrequests/karowan/feature/use httplocaleresolver for thymeleafviewsrenderer
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
Labels: type: bug
