Repository micronaut-projects/micronaut-views, pull requests merged in 2021-07, with the labels that each got.

#228 [views] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  views-rocker/build.gradle
Labels: relates-to: build

#242 feat: pebble - Added parallel tag support
  views-pebble/src/main/java/io/micronaut/views/pebble/PebbleEngineFactory.java
Labels: type: improvement

#244 replace nullability import
  test-suite/src/test/java/io/micronaut/views/model/security/MockAuthenticationProvider.java
Labels: type: improvement

#250 ci: update to GraalVM from 21.1.0 to 21.2.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#253 Fix GraalVM warning
  views-core/src/main/resources/META-INF/native-image/io.micronaut.views.model.security/native-image.properties
Labels: relates-to: graal

#255 New issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new_feature.yaml
  .github/ISSUE_TEMPLATE/other.yaml
Labels: relates-to: build
