Repository micronaut-projects/micronaut-views, pull requests merged in 2021-03, with the labels that each got.

#177 build: gradle from gradle-6.8.2 to gradle-6.8.3
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#188 [views] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#186 build: remove githubBranch
  gradle.properties
Labels: relates-to: build

#190 ci: setup project version to 2.3.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#191 ci: setup github branch to 2.5.x
  gradle.properties
Labels: relates-to: build

#183 build: bump up pebble to 3.1.5
  gradle.properties
Labels: relates-to: build

#182 build: bump up velocity to 2.3
  gradle.properties
Labels: relates-to: build

#180 build: bump up snake yaml to 1.28
  gradle.properties
Labels: relates-to: build, type: dependency-upgrade

#185 build: bump up micronaut-security to 2.3.1
  test-suite/build.gradle
  views-core/build.gradle
Labels: relates-to: build

#181 build: bump up freemarker from 2.3.30 to 2.3.31
  gradle.properties
Labels: relates-to: build

#184 build: bump up soy to 2021-02-01
  gradle.properties
Labels: relates-to: build

#192 refactor: use Micronaut Nullability annotations
  build.gradle
  gradle.properties
  views-core/src/main/java/io/micronaut/views/ViewUtils.java
  views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
  views-core/src/main/java/io/micronaut/views/csp/CspConfiguration.java
  views-core/src/main/java/io/micronaut/views/csp/CspFilter.java
  views-core/src/main/java/io/micronaut/views/model/ViewModelProcessor.java
  views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java
  views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessorConfiguration.java
  views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessorConfigurationProperties.java
  views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
  views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRendererConfigurationProperties.java
  views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java
  views-rocker/src/main/java/io/micronaut/views/rocker/RockerViewsRenderer.java
  views-soy/src/main/java/io/micronaut/views/soy/SoyFileSetProvider.java
  views-soy/src/main/java/io/micronaut/views/soy/SoyNamingMapProvider.java
  views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
  views-soy/src/main/java/io/micronaut/views/soy/SoyViewsRendererConfiguration.java
  views-soy/src/main/java/io/micronaut/views/soy/SoyViewsRendererConfigurationProperties.java
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/LinkBuilder.java
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
  views-velocity/src/main/java/io/micronaut/views/velocity/VelocityViewsRenderer.java
Labels: type: improvement

#194 refactor: make SoyFileSetProvider final
  views-soy/src/main/java/io/micronaut/views/soy/SoyViewsRendererConfigurationProperties.java
Labels: relates-to: soy, type: improvement

#193 remove license from soy file
  views-soy/src/test/resources/home.soy
Labels: relates-to: soy, type: docs

#196 build: move inject-java ann to root project
  build.gradle
  views-core/build.gradle
  views-freemarker/build.gradle
  views-handlebars/build.gradle
  views-pebble/build.gradle
  views-rocker/build.gradle
  views-soy/build.gradle
  views-thymeleaf/build.gradle
  views-velocity/build.gradle
Labels: relates-to: build

#195 build: remove duplicated dependency
  views-velocity/build.gradle
Labels: relates-to: build

#198 test: remove unecessary micronaut.security.enabled
  test-suite/src/test/groovy/views/model/security/SecurityViewModelProcessorSpec.groovy
Labels: type: improvement

#197 build: move ann asciidoc confi props to root build
  build.gradle
  views-freemarker/build.gradle
  views-handlebars/build.gradle
  views-pebble/build.gradle
  views-rocker/build.gradle
  views-soy/build.gradle
  views-thymeleaf/build.gradle
  views-velocity/build.gradle
Labels: relates-to: build

#200 doc: use configuration properties auto table
  src/main/docs/guide/views/soy.adoc
Labels: type: docs

#199 javadoc: add default values to javadoc
  views-soy/src/main/java/io/micronaut/views/soy/SoyViewsRendererConfigurationProperties.java
Labels: relates-to: soy, type: docs

#201 doc: add multi-language samples for Soy
  settings.gradle
  src/main/docs/guide/views/soy.adoc
  test-suite-groovy/build.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/CustomSoyFileSetProvider.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/SoyController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/soy/SoySpec.groovy
  test-suite-groovy/src/test/resources/views/home.soy
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/groovy/io/micronaut/doc/soy/CustomSoyFileSetProvider.groovy
  test-suite-kotlin/src/test/groovy/io/micronaut/doc/soy/SoyController.groovy
  test-suite-kotlin/src/test/groovy/io/micronaut/doc/soy/SoySpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/soy/CustomSoyFileSetProvider.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/soy/SoyController.kt
  test-suite-kotlin/src/test/resources/views/home.soy
  test-suite/build.gradle
  test-suite/src/test/groovy/io/micronaut/doc/soy/SoySpec.groovy
  test-suite/src/test/groovy/views/model/security/SecurityViewModelProcessorSpec.groovy
  test-suite/src/test/java/io/micronaut/docs/soy/CustomSoyFileSetProvider.java
  test-suite/src/test/java/io/micronaut/docs/soy/SoyController.java
  test-suite/src/test/resources/views/home.soy
  views-soy/src/test/groovy/io/micronaut/docs/ExampleSoyFileSetProvider.groovy
  views-soy/src/test/groovy/io/micronaut/docs/SoySauceViewRendererSpec.groovy
  views-soy/src/test/resources/views/home.soy
Labels: relates-to: soy, type: docs
