Repository micronaut-projects/micronaut-views, pull requests merged in 2022-03, with the labels that each got.

#359 Pass Locale to Pebble
  views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
  views-pebble/src/test/groovy/io/micronaut/docs/PebbleController.groovy
  views-pebble/src/test/groovy/io/micronaut/docs/PebbleViewsRendererSpec.groovy
  views-pebble/src/test/resources/i18n/messages_de.properties
  views-pebble/src/test/resources/i18n/messages_en.properties
  views-pebble/src/test/resources/i18n/messages_it.properties
  views-pebble/src/test/resources/views/i18n.txt
Labels: type: improvement

#351 build: dependency ugprade to minor and mayor versions
  gradle.properties
Labels: type: dependency-upgrade

#343 [views] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/sonarqube.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
  build.gradle
  config/checkstyle/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#362 ci: project version to 3.2.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#366 refactor: make HttpRequest parameter in ViewsRenderer nullable
  test-suite/src/test/java/views/NonHTMLViewRendererTest.java
  views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
  views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
  views-freemarker/src/test/groovy/io/micronaut/views/freemarker/FreemarkerViewRenderNullableRequestSpec.groovy
  views-freemarker/src/test/resources/views/tim.ftl
  views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java
  views-handlebars/src/test/groovy/io/micronaut/views/handlebars/HandlebarsViewRenderNullableRequestSpec.groovy
  views-handlebars/src/test/resources/views/tim.hbs
  views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
  views-jte/src/test/groovy/io/micronaut/jte/JteViewRenderNullableRequestSpec.groovy
  views-jte/src/test/resources/views/tim.jte
  views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
  views-pebble/src/test/groovy/io/micronaut/views/pebble/PebbleViewRenderNullableRequestSpec.groovy
  views-pebble/src/test/resources/views/tim.html
  views-rocker/src/main/java/io/micronaut/views/rocker/RockerViewsRenderer.java
  views-rocker/src/test/groovy/io/micronaut/views/rocker/RockerViewRenderNullableRequestSpec.groovy
  views-rocker/src/test/resources/views/tim.rocker.html
  views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
  views-soy/src/test/groovy/io/micronaut/views/soy/SoyViewRenderNullableRequestSpec.groovy
  views-soy/src/test/resources/views/home.soy
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/WebContext.java
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/WebEngineContext.java
  views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderNullableRequestSpec.groovy
  views-thymeleaf/src/test/resources/views/tim.html
  views-velocity/src/test/groovy/io/micronaut/views/velocity/VelocityViewRenderNullableRequestSpec.groovy
  views-velocity/src/test/resources/views/tim.vm
Labels: type: improvement

#372 build: update build plugin to 5.2.3
  settings.gradle
Labels: relates-to: build

#373 ci: checkstyle SupressionFilter
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: relates-to: build
