Repository micronaut-projects/micronaut-views, pull requests merged in 2023-10, with the labels that each got.

#601 [views] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#620 API to render form elements
  views-fieldset/src/main/java/io/micronaut/views/fields/InputEmailFormElement.java
  views-fieldset/src/main/java/io/micronaut/views/fields/InputPasswordFormElement.java
  views-fieldset/src/main/java/io/micronaut/views/fields/InputStringFormElement.java
  views-fieldset/src/main/java/io/micronaut/views/fields/InputTelFormElement.java
  views-fieldset/src/main/java/io/micronaut/views/fields/InputTextFormElement.java
  views-fieldset/src/main/java/io/micronaut/views/fields/InputUrlFormElement.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/FormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/HtmlAttribute.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputCheckboxFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputDateFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputDateTimeLocalFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputEmailFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputHiddenFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputNumberFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputPasswordFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputRadioFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputTelFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputTextFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/InputUrlFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/OptionFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/SelectFormElementRenderer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/TextareaFormElementRenderer.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/HtmlAttributeTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputCheckboxFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputDateFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputDateTimeFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputEmailFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputHiddenFormElementRenderTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputNumberFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputPasswordFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputRadioFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputTelFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputTextFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/InputUrlFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/OptionFormElementRenderTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/SelectFormElementRendererTest.java
  views-fieldset/src/test/java/io/micronaut/views/fields/render/TextareaFormElementRendererTest.java
Labels: type: enhancement

#631 turbo stream to its own filter and MessageBodyWriter
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboViewTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboViewTest.kt
  test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboViewTest.java
  views-core/src/main/java/io/micronaut/views/ViewsFilter.java
  views-core/src/main/java/io/micronaut/views/turbo/AbstractTurboRenderer.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamBuilderMessageBodyWriter.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamFilter.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamListOfBuilderMessageBodyWriter.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamMessageBodyWriter.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboView.java
  views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamSpec.groovy
  views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
  views-jte/src/test/groovy/io/micronaut/docs/JteViewRendererSpec.groovy
  views-rocker/src/test/groovy/io/micronaut/docs/RockerViewRendererSpec.groovy
  views-velocity/src/test/groovy/io/micronaut/docs/VelocityViewRendererSpec.groovy
Labels: type: improvement
