Repository micronaut-projects/micronaut-views, pull requests merged in 2023-05, with the labels that each got.

#522 Remove HTTP dependency from views-core
  config/accepted-api-changes.json
  settings.gradle
  src/main/docs/guide/breaks.adoc
  test-suite/src/test/java/io/micronaut/views/model/UnmodifiableFruitsController.java
  test-suite/src/test/java/views/NonHTMLViewRendererTest.java
  views-core/build.gradle
  views-core/src/main/java/io/micronaut/views/DefaultViewsModelDecorator.java
  views-core/src/main/java/io/micronaut/views/DefaultViewsRendererLocator.java
  views-core/src/main/java/io/micronaut/views/DefaultViewsResolver.java
  views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
  views-core/src/main/java/io/micronaut/views/csp/CspFilter.java
  views-core/src/main/java/io/micronaut/views/exceptions/ViewRenderingException.java
  views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java
  views-core/src/main/java/io/micronaut/views/turbo/DefaultTurboStreamRenderer.java
  views-core/src/test/groovy/io/micronaut/views/turbo/TurboFrameSpec.groovy
  views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamSpec.groovy
  views-freemarker/build.gradle
  views-freemarker/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
  views-freemarker/src/test/groovy/io/micronaut/views/freemarker/FreemarkerViewRenderNullableRequestSpec.groovy
  views-handlebars/build.gradle
  views-handlebars/src/main/java/io/micronaut/views/handlebars/HandlebarsViewsRenderer.java
  views-handlebars/src/test/groovy/io/micronaut/views/handlebars/HandlebarsViewRenderNullableRequestSpec.groovy
  views-jte/build.gradle
  views-jte/src/main/java/io/micronaut/views/jte/HtmlJteViewsRenderer.java
  views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
  views-jte/src/main/java/io/micronaut/views/jte/PlainJteViewsRenderer.java
  views-jte/src/test/groovy/io/micronaut/jte/JteViewRenderNullableRequestSpec.groovy
  views-pebble/build.gradle
  views-pebble/src/main/java/io/micronaut/views/pebble/PebbleViewsRenderer.java
  views-pebble/src/test/groovy/io/micronaut/views/pebble/PebbleViewRenderNullableRequestSpec.groovy
  views-rocker/build.gradle
  views-rocker/src/main/java/io/micronaut/views/rocker/RockerViewsRenderer.java
  views-rocker/src/test/groovy/io/micronaut/views/rocker/RockerViewRenderNullableRequestSpec.groovy
  views-soy/build.gradle
  views-soy/src/main/java/io/micronaut/views/soy/SoySauceViewsRenderer.java
  views-thymeleaf/build.gradle
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
  views-velocity/src/main/java/io/micronaut/views/velocity/VelocityViewsRenderer.java
  views-velocity/src/test/groovy/io/micronaut/views/velocity/VelocityViewRenderNullableRequestSpec.groovy
Labels: status: next major version, type: breaking

#529 Micronaut Framework 4.0.0-M5
  build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.views-base.gradle
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  test-suite/build.gradle
  views-core/build.gradle
  views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
  views-velocity/build.gradle
Labels: type: dependency-upgrade

#530 ci: GitHub Actions sync
  .github/workflows/release.yml
Labels: relates-to: build

#532 Make ViewRendererLocator API don't depend on MediaType
  config/accepted-api-changes.json
  gradle/libs.versions.toml
  settings.gradle
  test-suite-http/build.gradle
  test-suite-http/src/test/java/io/micronaut/security/http/HttpOptionalTest.java
  test-suite-http/src/test/resources/logback.xml
  test-suite/src/test/java/io/micronaut/views/model/security/MockAuthenticationProvider.java
  views-core/src/main/java/io/micronaut/views/DefaultViewsRendererLocator.java
  views-core/src/main/java/io/micronaut/views/ViewsFilter.java
  views-core/src/main/java/io/micronaut/views/ViewsRendererLocator.java
  views-core/src/main/java/io/micronaut/views/exceptions/ViewNotFoundException.java
  views-core/src/main/java/io/micronaut/views/turbo/AbstractTurboRenderer.java
  views-core/src/main/java/io/micronaut/views/turbo/DefaultTurboFrameRenderer.java
  views-core/src/main/java/io/micronaut/views/turbo/DefaultTurboStreamRenderer.java
Labels: type: improvement

#534 [views] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
