Repository micronaut-projects/micronaut-views, pull requests merged in 2023-11, with the labels that each got.

#635 doc: FORM Generation example
  gradle.properties
  src/main/docs/guide/toc.yml
  src/main/docs/guide/views/fieldset.adoc
  src/main/docs/guide/views/fieldset/fieldsetExample.adoc
  test-suite-freemarker-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/FreemarkerSuite.java
  test-suite-thymeleaf-fieldset/build.gradle.kts
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/Book.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookController.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookControllerTest.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookRepository.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookSave.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/ThymeleafSuite.java
  test-suite-thymeleaf-fieldset/src/test/resources/views/books/create.html
  test-suite-thymeleaf-fieldset/src/test/resources/views/books/list.html
  test-suite-thymeleaf-fieldset/src/test/resources/views/layout.html
Labels: type: docs

#639 doc: Document fieldset annotations
  src/main/docs/guide/toc.yml
  src/main/docs/guide/views/fieldset/fieldsetAnnotations.adoc
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookController.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookControllerTest.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/BookSave.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/Login.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/TestUtils.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/UserController.java
  test-suite-thymeleaf-fieldset/src/test/java/io/micronaut/views/fields/thymeleaf/UsersControllerTest.java
  test-suite-thymeleaf-fieldset/src/test/resources/logback.xml
  test-suite-thymeleaf-fieldset/src/test/resources/views/users/auth.html
  views-fieldset/src/main/java/io/micronaut/views/fields/annotations/InputRadio.java
  views-fieldset/src/main/java/io/micronaut/views/fields/annotations/Textarea.java
Labels: type: docs

#645 [views] Update common files for branch master
  .github/workflows/release.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
Labels: relates-to: build

#617 Update jte to version 3.1.3
  gradle/libs.versions.toml
  src/main/docs/guide/views/templates/jte.adoc
  test-suite-graal/test-suite-graal-jte/build.gradle
  views-jte/src/main/java/io/micronaut/views/jte/JteViewsRendererConfiguration.java
  views-jte/src/main/java/io/micronaut/views/jte/PlainJteViewsRenderer.java
Labels: type: dependency-upgrade, type: breaking

#656 use AutoPopulated as String to avoid requiring data
  views-fieldset/build.gradle.kts
  views-fieldset/src/main/java/io/micronaut/views/fields/DefaultFieldGenerator.java
  views-fieldset/src/main/java/io/micronaut/views/fields/render/views/package-info.java
  views-fieldset/src/test/java/io/micronaut/views/fields/formsexamples/AutomaticallyPopulatedTest.java
Labels: type: bug
