Repository micronaut-projects/micronaut-views, pull requests merged in 2023-09, with the labels that each got.

#590 Jstachio Support
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/toc.yml
  src/main/docs/guide/views/templates/jstachio.adoc
  src/main/docs/guide/views/templates/jstachio/jstachioExample.adoc
  src/main/docs/guide/views/templates/jstachio/jstachioInstallation.adoc
  views-core/src/main/java/io/micronaut/views/ViewsFilter.java
  views-jstachio/build.gradle.kts
  views-jstachio/src/main/java/io/micronaut/views/jstachio/JStachioFactory.java
  views-jstachio/src/main/java/io/micronaut/views/jstachio/JStachioMessageBodyWriter.java
  views-jstachio/src/main/java/io/micronaut/views/jstachio/package-info.java
  views-jstachio/src/test/groovy/io/micronaut/views/jstachio/HtmlControllerSpec.groovy
  views-jstachio/src/test/groovy/io/micronaut/views/jstachio/clazz/HomeControllerSpec.groovy
  views-jstachio/src/test/groovy/io/micronaut/views/jstachio/pkginfo/HomeControllerSpec.groovy
  views-jstachio/src/test/java/io/micronaut/views/jstachio/HtmlController.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/HtmlViewsRenderer.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/Person.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/PersonMessageBodyWriter.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/clazz/HomeController.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/clazz/HomeModel.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/clazz/MicronautJStacheConfig.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/pkginfo/HomeController.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/pkginfo/HomeModel.java
  views-jstachio/src/test/java/io/micronaut/views/jstachio/pkginfo/package-info.java
  views-jstachio/src/test/resources/logback.xml
  views-jstachio/src/test/resources/views/home.mustache
Labels: type: enhancement

#597 [views] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#607 Passing a List as the model to ModelAndView results in an IntrospectionException
  src/main/docs/guide/views.adoc
  views-thymeleaf/src/test/groovy/io/micronaut/docs/ThymeleafViewRendererSpec.groovy
Labels: type: docs
