Repository micronaut-projects/micronaut-views, pull requests merged in 2024-04, with the labels that each got.

#766 [views] Update common files for branch 5.3.x
  .github/workflows/graalvm-dev.yml
Labels: relates-to: build

#773 add new "morph" and "refresh" action types for turbo-stream, issue #772
  views-core/src/main/java/io/micronaut/views/turbo/TurboStream.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamAction.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboView.java
  views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamSpec.groovy
Labels: type: improvement

#775 [views] Update common files for branch 5.3.x
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#778 fix: turbo stream processing should use decoration
  test-suite/src/test/java/io/micronaut/views/ModelAndViewTest.java
  views-core/src/main/java/io/micronaut/views/turbo/DefaultTurboStreamRenderer.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamBuilderMessageBodyWriter.java
  views-core/src/main/java/io/micronaut/views/turbo/TurboStreamListOfBuilderMessageBodyWriter.java
Labels: type: bug

#784 feat: add missing morph and refresh methods
  views-core/src/main/java/io/micronaut/views/turbo/TurboStream.java
  views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamSpec.groovy
Labels: type: improvement

#797 Fix misconfigured api link in docs.
  src/main/docs/guide/views/htmx/outOfBandSwaps.adoc
Labels: type: docs

#796 fix: Turbo Frame processing should use decoration
  test-suite/src/test/java/io/micronaut/views/ModelAndViewTest.java
  views-core/src/main/java/io/micronaut/views/turbo/AbstractTurboRenderer.java
  views-core/src/main/java/io/micronaut/views/turbo/DefaultTurboFrameRenderer.java
Labels: type: bug

#799 docs: clarify how to add annotation processor dependencies for Kotlin and Groovy projects
  src/main/docs/guide/views/templates/jstachio/jstachioInstallation.adoc
Labels: type: docs
