Repository micronaut-projects/micronaut-views, pull requests merged in 2024-10, with the labels that each got.

#908 [views] Update common files for branch 5.6.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#898 Describe request attribute containing CSP nonce
  src/main/docs/guide/views/security/csp.adoc
Labels: type: docs

#916 generate hidden input for csrftoken
  src/main/docs/guide/toc.yml
  src/main/docs/guide/views/fieldset/csrfHidden.adoc
  test-suite-csrf/build.gradle.kts
  test-suite-csrf/src/test/java/io/micronaut/views/tests/security/csrf/CsrfFormGenerationTest.java
  views-fieldset/build.gradle.kts
  views-fieldset/src/main/java/io/micronaut/views/fields/CsrfFieldsetConsumer.java
  views-fieldset/src/main/java/io/micronaut/views/fields/DefaultFieldGenerator.java
  views-fieldset/src/main/java/io/micronaut/views/fields/FieldsetConsumer.java
Labels: type: enhancement
