Repository micronaut-projects/micronaut-views, pull requests merged in 2024-08, with the labels that each got.

#850 build: update org.json:json to patched version
  gradle/libs.versions.toml
  views-soy/build.gradle.kts
Labels: type: dependency-upgrade

#848 [views] Update common files for branch 5.4.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#851 ReactJS: Fixes to proxy object wrapping
  views-react/src/main/java/io/micronaut/views/react/ProxyObjectWithIntrospectableSupport.java
  views-react/src/main/java/io/micronaut/views/react/ReactViewsRenderer.java
  views-react/src/test/groovy/io/micronaut/views/react/IntrospectableBeansAreProxiedSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/PreactViewRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/ReactViewRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/SandboxReactRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/TestProps.groovy
  views-react/src/test/java/io/micronaut/views/react/SomeBean.java
Labels: type: bug

#853 [views] Update common files for branch 5.4.x
  .github/workflows/release.yml
Labels: relates-to: build
