Repository micronaut-projects/micronaut-views, pull requests merged in 2024-02, with the labels that each got.

#701 Remove unused testcontainers from catalog
  gradle/libs.versions.toml
Labels: relates-to: build

#690 [views] Update common files for branch master
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build

#678 Add ability to render thymeleaf fragments
  views-thymeleaf/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
  views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderFragmentSpec.groovy
  views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/ThymeleafViewRenderNullableRequestSpec.groovy
  views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/WriteableUtils.groovy
  views-thymeleaf/src/test/groovy/io/micronaut/views/thymeleaf/web/LinkTestController.groovy
  views-thymeleaf/src/test/resources/views/fragment.html
Labels: type: enhancement

#705 docs: Add a test for POST with TurboStreams
  src/main/docs/guide/views/turbo/turboFrameBuilder.adoc
  src/main/docs/guide/views/turbo/turboFrameView.adoc
  src/main/docs/guide/views/turbo/turboStreamContentType.adoc
  src/main/docs/guide/views/turbo/turboStreamFluidApi.adoc
  src/main/docs/guide/views/turbo/turboStreamTemplate.adoc
  src/main/docs/guide/views/turbo/turboView.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/Fruit.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/Message.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboFrameBuilderTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboFrameTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboStreamTemplateTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboStreamTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/views/docs/turbo/TurboViewTest.groovy
  test-suite-groovy/src/test/resources/views/fruit.vm
  test-suite-groovy/src/test/resources/views/view.vm
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/Fruit.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/Message.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboFrameBuilderTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboFrameTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboStreamTemplateTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboStreamTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/views/docs/turbo/TurboViewTest.kt
  test-suite-kotlin/src/test/resources/views/fruit.vm
  test-suite-kotlin/src/test/resources/views/view.vm
  test-suite/src/test/java/io/micronaut/views/docs/turbo/Fruit.java
  test-suite/src/test/java/io/micronaut/views/docs/turbo/Message.java
  test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboFrameBuilderTest.java
  test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboFrameTest.java
  test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboStreamTemplateTest.java
  test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboStreamTest.java
  test-suite/src/test/java/io/micronaut/views/docs/turbo/TurboViewTest.java
  test-suite/src/test/resources/views/edit.vm
  test-suite/src/test/resources/views/form.vm
  test-suite/src/test/resources/views/fruit.vm
  test-suite/src/test/resources/views/fruits.vm
  test-suite/src/test/resources/views/view.vm
Labels: type: docs

#719 [views] Update common files for branch master
  .github/workflows/graalvm-dev.yml
Labels: relates-to: build
