Repository micronaut-projects/micronaut-views, pull requests merged in 2024-07, with the labels that each got.

#830 [views] Update common files for branch 5.4.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#833 React Renderer: use the resource resolver API to locate the server bundle
  src/main/docs/guide/views/templates/react/reactpreparingjs.adoc
  src/main/docs/guide/views/templates/react/reactsettingproperties.adoc
  views-react/src/main/java/io/micronaut/views/react/JSBundlePaths.java
  views-react/src/main/java/io/micronaut/views/react/JSContextPool.java
  views-react/src/main/java/io/micronaut/views/react/ReactViewsRendererConfiguration.java
  views-react/src/test/groovy/io/micronaut/views/react/PreactViewRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/ReactViewRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/SandboxReactRenderSpec.groovy
Labels: type: improvement

#835 remove initialize-at-runtime definitions
  views-core/src/main/resources/META-INF/native-image/io.micronaut.views.model.security/native-image.properties
Labels: type: improvement, relates-to: graal

#840 [views] Update common files for branch 5.4.x
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
