Repository micronaut-projects/micronaut-views, pull requests merged in 2024-05, with the labels that each got.

#801 Set charset to utf-8 when we default to text/html
  views-core/src/main/java/io/micronaut/views/ViewsFilter.java
  views-core/src/test/groovy/io/micronaut/views/turbo/TurboStreamSpec.groovy
  views-rocker/src/test/groovy/io/micronaut/docs/RockerController.groovy
  views-rocker/src/test/groovy/io/micronaut/docs/RockerViewRendererSpec.groovy
Labels: type: bug

#770 Feature: Support for React JS server side rendering
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/toc.yml
  src/main/docs/guide/views/templates/react.adoc
  src/main/docs/guide/views/templates/react/preact.adoc
  src/main/docs/guide/views/templates/react/reactheadmanagers.adoc
  src/main/docs/guide/views/templates/react/reactpreparingjs.adoc
  src/main/docs/guide/views/templates/react/reactrenderscripts.adoc
  src/main/docs/guide/views/templates/react/reactsettingproperties.adoc
  src/main/docs/guide/views/templates/react/reacttodo.adoc
  views-react/.gitignore
  views-react/README.md
  views-react/build.gradle
  views-react/src/main/java/io/micronaut/views/react/CompiledJS.java
  views-react/src/main/java/io/micronaut/views/react/IntrospectableToPolyglotObject.java
  views-react/src/main/java/io/micronaut/views/react/JSBundlePaths.java
  views-react/src/main/java/io/micronaut/views/react/JSContext.java
  views-react/src/main/java/io/micronaut/views/react/JSContextPool.java
  views-react/src/main/java/io/micronaut/views/react/JSEngineLogHandler.java
  views-react/src/main/java/io/micronaut/views/react/JSSandboxing.java
  views-react/src/main/java/io/micronaut/views/react/OutputStreamToSLF4J.java
  views-react/src/main/java/io/micronaut/views/react/ReactViewsRenderer.java
  views-react/src/main/java/io/micronaut/views/react/ReactViewsRendererConfiguration.java
  views-react/src/main/resources/io/micronaut/views/react/preact.js
  views-react/src/main/resources/io/micronaut/views/react/react.js
  views-react/src/test/groovy/io/micronaut/views/react/PreactViewRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/ReactViewRenderSpec.groovy
  views-react/src/test/groovy/io/micronaut/views/react/SandboxReactRenderSpec.groovy
  views-react/src/test/java/io/micronaut/views/react/SomeBean.java
  views-react/src/test/js/client.js
  views-react/src/test/js/client.preact.js
  views-react/src/test/js/components/App.js
  views-react/src/test/js/package.json
  views-react/src/test/js/server.js
  views-react/src/test/js/server.preact.js
  views-react/src/test/js/webpack.client.js
  views-react/src/test/js/webpack.client.preact.js
  views-react/src/test/js/webpack.server.js
  views-react/src/test/js/webpack.server.preact.js
  views-react/src/test/resources/application-test.properties
Labels: type: enhancement

#798 [views] Update common files for branch 5.4.x
  .github/workflows/gradle.yml
Labels: relates-to: build
